{{- if .Values.createNamespace }}
{{- if and (ne .Values.functionNamespace "default") (ne .Values.functionNamespace "") }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ template "fission-function-ns" . }}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
  labels:
    name: fission-function
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
    {{- if .Values.enableIstio }}
    istio-injection: enabled
    {{- end }}
{{- end}}

---

{{- if and (ne .Values.builderNamespace "default") (ne .Values.builderNamespace "") }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ template "fission-builder-ns" . }}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
  labels:
    name: fission-builder
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
    {{- if .Values.enableIstio }}
    istio-injection: enabled
    {{- end }}
{{- end }}
{{- end }}
