apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-fetcher
  namespace: {{ template "fission-function-ns" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-builder
  namespace: {{ template "fission-builder-ns" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
