apiVersion: v1
kind: ServiceAccount
metadata:
  name: fission-preupgrade
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-1"
