apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  labels:
    svc: webhook-service
    application: fission-webhook
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: 443
    targetPort: 9443
  selector:
    svc: webhook-service
