{{- if .Values.authentication.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: router
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": pre-install
data:
  username: {{ .Values.authentication.authUsername | b64enc | quote }}
  password: {{ randAlphaNum 20 | b64enc | quote }}
  jwtSigningKey: {{ .Values.authentication.jwtSigningKey | b64enc | quote }}
{{- end }}
