apiVersion: v1
kind: Service
metadata:
  name: router
  labels:
    svc: router
    application: fission-router
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
{{- if .Values.router.svcAnnotations }}
{{ toYaml .Values.router.svcAnnotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.routerServiceType }}
  ports:
  - port: 80
    targetPort: 8888
{{- if eq .Values.routerServiceType "NodePort" }}
    nodePort: {{ .Values.routerPort }}
{{- end }}
  selector:
    svc: router
