{{- if .Values.influxdb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: influxdb
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
type: Opaque
data:
  username: {{ .Values.logger.influxdbAdmin | b64enc | quote }}
  password: {{ randAlphaNum 20 | b64enc | quote }}
{{- end }}
