{{- if .Values.controller.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
    svc: controller
    application: fission-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: 80
    targetPort: 8888
{{- if eq .Values.serviceType "NodePort" }}
    nodePort: {{ .Values.controllerPort }}
{{- end }}
  selector:
    svc: controller
{{- end -}}
